// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import ConfirmationController from "./confirmation_controller.js"
application.register("confirmation", ConfirmationController)

import HeaderController from "./header_controller.js"
application.register("header", HeaderController)
